services:
  - type: web
    name: imei-report
    env: node
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        value: your-secret-key
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: your-postgres-url
